server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:8081/calendar
    driver-class-name: org.postgresql.Driver
    password: root
    username: root

  liquibase:
    change-log:
    url: jdbc:postgresql://localhost:8081/calendar
    user: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
